### ISSUE TITLE
Databinding too ?

### ISSUE THREAD

**Issue by gedw99** [terrier989/dart-universal_html#1]
Thanks for this and universal IO library.

Does this provide a way to do databinding of JSON with HTML at runtime - loosely typed 

I am not sure of the preferred databinding but mustache is a pretty well know runtime databinding language and there is a dart library for it :)

If you have other ideas I am all ears :)

**Comment by terrier989** [comment]
Thanks for feedback!

This package simply implements 'dart:html' API in non-browser platforms. If 'dart:html' contains something you are looking for, then it could be implemented in this package.
